### ISSUE TITLE
Broken recipe

### ISSUE THREAD

**Issue by TDMoce** [Overclock-Studio/Better_Recipes_x10#11]
**Alternate Rod recipe bugged/broken**
Recipe showing rods to make rods
![broken mod recipe](https://github.com/user-attachments/assets/ad20f22c-2c11-4c2c-9d84-483d595b8a88)

**To Reproduce**
1. Go to the crafting bench and enter its menu
2. Scroll down to alternate iron rods
3. Craft the iron rods with iron rods
4. When you finish crafting the game will stall then crash or as found on a new save that the crafter will continue recycling the rods as none are consumed

**Expected behavior**
When opening the crafting bench and selecting the alternate iron rod it should show as intended and has done in previous saves, 1 iron ingot making 10 iron rods

**Desktop (Steam version 1.0.0.5):**
 - Better Alternate Recipes version 1.2.0

**Additional context**
New save started to test new layouts and found this issue, previous save was working without issue, made a new save to test if that save was corrupt and the new save had the same issue

**Comment by TheFarawayDev** [comment]
The issue has been resolved, simply update to v1.2.1!
