### ISSUE TITLE
Think you missed some recipes

### ISSUE THREAD

**Issue by L05T50UL95** [Overclock-Studio/Better_Recipes_x10#12]
The Blue Slug Power Shard,Copper Sheet, Modular Frame, Rotor and Solid Biofuel still come up as X10 which are in Tier 2.

![Screenshot 2024-11-07 040504](https://github.com/user-attachments/assets/c70a20bf-f062-4ad7-a118-4e34945034aa)
![Screenshot 2024-11-07 033635](https://github.com/user-attachments/assets/444deab6-c4a5-4c05-9bf6-f3e5b5db0afa)
![Screenshot 2024-11-07 033647](https://github.com/user-attachments/assets/41588d0f-49e8-40cc-a438-f790d359a6be)
![Screenshot 2024-11-07 033658](https://github.com/user-attachments/assets/5777e41e-2fcf-4974-89a9-4c5587b40382)
![Screenshot 2024-11-07 033716](https://github.com/user-attachments/assets/5117045f-58cb-439b-96b3-2ea32ca050b6)
![Screenshot 2024-11-07 034205](https://github.com/user-attachments/assets/aac938ed-fe6a-4122-af92-7fadea4d5a24)

Edit: Added Blue Slug Power Shard coming up as X10 still

**Comment by TheFarawayDev** [comment]
They haven't been published yet to SMR I plan to today!

**Comment by L05T50UL95** [comment]
ah ok, i assumed they were in the mod since you put it in discord as completed
